name: Lint

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  lint:
    uses: OpenVoiceOS/gh-automations/.github/workflows/lint.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      ruff: true
      pre_commit: false   # set true if .pre-commit-config.yaml exists
